# Generated by Django 3.2.4 on 2021-06-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_name', models.CharField(max_length=250)),
                ('film_desc', models.TextField()),
                ('film_year', models.IntegerField()),
                ('film_icon', models.ImageField(upload_to='')),
            ],
        ),
    ]
